language: php

sudo: true
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

env:
  global:
    - TARGET=unit

matrix:
  fast_finish: true
  include:
    - php: '7.2'
      env: TARGET=behat

  allow_failures:
    - php: nightly

install:
  - composer update --dev --prefer-lowest

script:
  - composer tests:${TARGET}
