language: php
sudo: true

services:
  - rabbitmq

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

env:
  global:
    - TARGET=unit

matrix:
  fast_finish: true
  include:
    - php: '7.2'
      env: TARGET=behat
    - php: '7.2'
      env: TARGET=e2e

  allow_failures:
    - php: nightly

before_install:
  - echo "extension=amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer update --dev --prefer-lowest

script:
  - composer tests:${TARGET}
