language: php
sudo: true

services:
  - rabbitmq

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

env:
  global:
    - TARGET=unit

matrix:
  fast_finish: true
  include:
    - php: '7.2'
      env: TARGET=behat
    - php: '7.2'
      env: TARGET=e2e

  allow_failures:
    - php: nightly

before_install:
  - if [ "${COVERAGE}" == "e2e" ]; then

    fi

install:
  - composer update --dev --prefer-lowest

script:
  - composer tests:${TARGET}
